parameters:
    weather_api_url: 'http://api.openweathermap.org/data/2.5/weather'
    weather_api_key: '49ca2e30e88cb6acb54337290fa98b20'
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Messenger\MessageHandler\:
        resource: '../src/Messenger/MessageHandler'
        autoconfigure: false
        tags: [{ name: messenger.message_handler, bus: command.bus }]

    App\Messenger\EventHandler\:
        resource: '../src/Messenger/EventHandler'
        autoconfigure: false
        tags: [{ name: messenger.message_handler, bus: event.bus }]

    App\Messenger\QueryHandler\:
        resource: '../src/Messenger/QueryHandler'
        autoconfigure: false
        tags: [{ name: messenger.message_handler, bus: query.bus }]


