framework:
    messenger:

        default_bus: command.bus
        buses:
            command.bus: ~
            event.bus: ~
            query.bus: ~

        transports:
            weather_queue: '%env(MESSENGER_TRANSPORT_DSN)%'
            weather_projection: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            'App\Messenger\Message\GetWeatherForLocation': weather_queue
            'App\Messenger\Event\ForecastHasBeenDownloaded': weather_projection
